# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    administrator:
                        password: $2y$12$EKd0bsTLyWe9s28Jpo0MAe9Z0aazz8CHzACP6QalgJVMxhPvVZwL.
                        # wachtwoord = admin1
                        roles: 'ROLE_USER, ROLE_ADMIN'
                    inkoper:
                        password: $2y$12$07O611L3z15IueCNMzMDDuH33oP7Kqx3Hc617xfgGwApJN7O4r5Z6
                        # wachtwoord = inkoper1
                        roles: 'ROLE_INKOPER'
                    magazijnmeester:
                        password: $2y$12$ihyyiITk0OSNRbzKuSIhxOf83F0sKY57dJh5ZiHw7mZLnJPZK2KKm
                        # wachtwoord = magazijn1
                        roles: 'ROLE_MAGAZIJN'   
                    verkoper:
                        password: $2y$12$/Q7wRSc/v3OnIbTmrpL52u7xcEFTGCqvH0WSnDJ/wzX7v9EQOKWOK
                        # wachtwoord = verkoper1
                        roles: 'ROLE_VERKOPER'     
                    user:
                        password: $2y$12$yn.PSur5hQSWSPRByHE4i.rVdaOQ4OyJiJpO/NETqR/GcrPPkhWGG
                        # wachtwoord = user1
                        roles: 'ROLE_USER'    

    role_hierarchy: 
        ROLE_ADMIN: [ROLE_USER, ROLE_MAGAZIJN, ROLE_VERKOPER, ROLE_INKOPER]
        ROLE_INKOPER: [ROLE_INKOPER]
        ROLE_MAGAZIJN: [ROLE_MAGAZIJN]
        ROLE_VERKOPER: [ROLE_VERKOPER]
        ROLE_USER: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/magazijnlocatie/alle, roles: ROLE_MAGAZIJN }
        - { path: ^/alle/bestelformulier, roles: ROLE_MAGAZIJN }
        - { path: ^/artikel/tekort, roles: ROLE_INKOPER }
        - { path: ^/searchArtikel, roles: ROLE_INKOPER }
        - { path: ^/alle/bestelformulier, roles: ROLE_VERKOPER }
        - { path: ^/artikel/alle, roles: ROLE_VERKOPER }
        - { path: ^/artikel/tekort, roles: ROLE_VERKOPER }
       

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                always_use_default_target_path: true
            logout:
                path:    /logout
                target:  /login
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
