# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$bDX00WmJpmb1zBbmRMDOkeoVl3m8I2ZokRruNMROP1QFczIjlVov6
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                always_use_default_target_path: true
            logout:
                path:    /logout
                target:  /login
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
